version: '3.8'
networks:
    my-network:
        driver: bridge
services:

    wordpress:
        image: wordpress:php8.2-fpm-alpine
        container_name: wordpress-${SITE_NAME}
        volumes:
            - ./wordpress:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_CONFIG_EXTRA: |
                define( 'WP_CACHE_KEY_SALT', '${SITE_NAME}' );
                define( 'WP_CACHE', true );
        networks:
            - my-network
        depends_on:
            - memcached

    memcached:
        image: memcached:1.6.22-alpine
        container_name: memcached-${SITE_NAME}
        ports:
            - "11211:11211"
        networks:
            - my-network
            
    mysql:
        image: mysql:8.0
        container_name: mysql-${SITE_NAME}
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
        networks:
            - my-network

    phpmyadmin:
        image: phpmyadmin:5.2.1
        container_name: myadmin-${SITE_NAME}
        ports:
            - "8080:80"
        environment:
            PMA_HOST: ${WORDPRESS_DB_HOST}
            PMA_USER: ${WORDPRESS_DB_USER}
            PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        networks:
            - my-network

    apache:
        image: wordpress:latest
        container_name: apache-${SITE_NAME}
        volumes:
            - ./wordpress:/var/www/html:rw
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
        networks:
            - my-network
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        ports:
            - 8087:80